version: '2'
services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: bundle exec puma -t 5:5 -p 3000 -e development
    ports:
      - "8080:3000"
    depends_on:
      - database

  database:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data